apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-s3www
  namespace: {{ .Release.Namespace }}
  labels:
    istio.io/use-waypoint: waypoint
spec:
  selector:
    app: s3www
  ports:
    - port: {{ .Values.s3www.service.port }}
      targetPort: {{ .Values.s3www.service.targetPort | default .Values.s3www.service.port }}
      protocol: TCP