apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.existingSecret | default (print .Release.Name "-minio-credentials") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: credentials
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  rootUser: {{ randAlphaNum 16 | quote }}
  rootPassword: {{ randAlphaNum 32 | quote }}
  