---
gateway:
  # This is the Istio Gateway configuration for the application.
  namespace: istio-system
  # The name of the Gateway resource.
  name: waypoint
  # The URL that the Gateway will serve.
  url: example.com

s3www:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  replicaCount: 1
  image:
    repository: y4m4/s3www
    tag: latest
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 300Mi
  deployment:
    labels: {}
    annotations:
      description: s3www serving static bucket content
  podLabels: {}
  podAnnotations: {}
  service:
    port: 8080
    targetPort: 8080

minio:
  image:
    repository: quay.io/minio/minio
    tag: latest
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  replicas: 1
  mode: standalone
  serviceName: myapp-minio
  ## Disable TLS, the mTLS provides secure communication.
  tls:
    enabled: false
  existingSecret: myapp-minio-credentials
  buckets:
    - name: web
      policy: readwrite
      purge: false
      versioning: false
      objectlocking: false
  users: []
  consoleService:
    type: ClusterIP
    port: "9001"
  persistence:
    enabled: true
    size: 1Gi
